### ISSUE TITLE
First set of questions

### ISSUE THREAD

**Issue by abreathingcorpse** [Penaz91/bubblewrap#1]
First of all, I'll be blunt here.
I didn't spent enough time to check the details of the code and understanding it fully.
Just enough to understand things at what I'd like to call, a Level 0 of understanding (like the tip of the iceberg).
Hope that's enough for me to start asking questions.

- I couldn't find any Definition nor a declaration for **RAND_MAX**. So I'm wondering, how does _getRandFloat()_ works?
- Is there a reason why you prefer to use pointers on your function arguments? For instance why _setPoppedTexture(Vertex* quad)_ instead of simply using the **Vertex quad** argument.
- Could you please explain the following line? `sf::Vertex* quad = &(*bubbles)[currentTile * 4];`.
I understand that `currentTile` is, well, the current tile, which was taken by converting the matrix into a vector.
`quad` is defined within this scope and deleted when you move out of the scope.
`bubbles` is a VertexArray, which is kind of like an std::vector which holds `PrimitiveType::Quads`. So, my question is:
`&(*bubbles)`. Are you getting the reference of the value address from the bubble pointer? This is somewhat confusing.

BTW, thank you for spending the time on adding the comments.

**Comment by Penaz91** [comment]
No worries, there's quite a bit of C++ "magic" happening in the code, I'll try to explain it as much as possible here.

> I couldn't find any Definition nor a declaration for RAND_MAX. So I'm wondering, how does getRandFloat() works?

That is a C++ preprocessor macro, so it is defined in the language itself: https://en.cppreference.com/w/cpp/numeric/random/RAND_MAX

> Is there a reason why you prefer to use pointers on your function arguments?

That is because it allows me to modify items directly, without having to work on a copy first, return it, and then re-assign it. It's a lot more memory-efficient and performing.

> Could you please explain the following line? sf::Vertex* quad = &(*bubbles)[currentTile * 4];

That is a bit of pointer magic to adapt the output of `operator[]` to the type I wanted.

`bubbles` is of type `sf::VertexArray*`, to be able to use `operator[]` I need an `sf::VertexArray`, so I de-reference the pointer using `(*bubbles)`.

Then I use the `[]` operator to obtain the Vertex, the only issue is that `operator[]` returns a `Vertex&` type (reference to Vertex), while I want a `Vertex*` type (pointer to Vertex). That's what the `&` operator does.

In essence, the `operator[]` in SFML gives me a direct reference to the item that I can use as if I was using the original object, but instead I want the object memory address (the pointer).

This can be a real pain to understand until the concepts of "L-Value" and "R-value" click, as well as how to switch from one to the other.

> bubbles is a VertexArray, which is kind of like an std::vector which holds PrimitiveType::Quads

This is wrong, although I understand the source of the confusion. VertexArray is a structure that contains `sf::Vertex` instances. The `PrimitiveType::Quads` that is passed is used for some internal checks.

Reference API: https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1VertexArray.php

**Comment by abreathingcorpse** [comment]
> That is a C++ preprocessor macro, so it is defined in the language itself: https://en.cppreference.com/w/cpp/numeric/random/RAND_MAX

Oh, so what you are doing is normalizing the randomness. In other words `uniform` has a domain of [0,1].

> That is because it allows me to modify items directly, without having to work on a copy first, return it, and then re-assign it. It's a lot more memory-efficient and performing.

So you are saying that whenever one modifies an object inside a function then one is modifying a copy of it and not the object itself? I believe that Python does this and one needs to use a strong copy to avoid this issue.

> This can be a real pain to understand until the concepts of "L-Value" and "R-value" click, as well as how to switch from one to the other.

Right, I still struggle with the difference between a pointer and a reference. To my understanding the `var*` is a pointer, that is, it points to the memory address of var. While reference I'm still unsure of its uses.

That said I think I undertand the following magic a bit better:
> bubbles is of type sf::VertexArray*, to be able to use operator[] I need an sf::VertexArray, so I de-reference the pointer using (*bubbles).

>Then I use the [] operator to obtain the Vertex, the only issue is that operator[] returns a Vertex& type (reference to Vertex), while I want a Vertex* type (pointer to Vertex). That's what the & operator does.

You are seeking a Vertex* instead of a Vertex&, so you need to use **&** at the left side of `(*bubbles)[]` so that you pass the memory address.

> >bubbles is a VertexArray, which is kind of like an std::vector which holds PrimitiveType::Quads

>This is wrong, although I understand the source of the confusion. VertexArray is a structure that contains sf::Vertex instances. The PrimitiveType::Quads that is passed is used for some internal checks.

Sorry if I said something barbaric. The docs say:
> sf::VertexArray is a very simple wrapper around a dynamic array of vertices and a primitives type.

My mind kind of puts them around a similar place to a std::vector. On std::vector one can use _push_back_, which also reminds me to Python's list.append(). Furthermore, I seem to recall that std::vector uses `Template`, and I figured that the `Primitive::Quads` were similar to the `T` of the template.

**Comment by Penaz91** [comment]
> Oh, so what you are doing is normalizing the randomness. In other words uniform has a domain of [0,1].

Exactly.

> So you are saying that whenever one modifies an object inside a function then one is modifying a copy of it and not the object itself?

Essentially using pointers/references switches the way you pass parameters from "passing by value" (where you create a copy of the class/primitive... before calling the function and then return the result) to "passing by reference" (where you just say "The data to edit is there" and edit in in-place).

This means that functions that use references and pointers as parameters have so-called "side effects", this means that even if they have a `void` return type, they can edit data outside their scope.

> I believe that Python does this and one needs to use a strong copy to avoid this issue.

Python is a bit of a weird case, it usually use "pass by reference", that's why you need to use "deep copy" facilities sometimes, in case it ends up copying only the "first layer" of a data structure.

For instance: if you copy over a tree, you may end up with two copies of the same structure, but actually it's the same tree in memory, just with two roots, pointing to the same "branches". This is usually called "memory aliasing" (the fact that you're accessing the same data using two different "aliases").

> Right, I still struggle with the difference between a pointer and a reference. To my understanding the var* is a pointer, that is, it points to the memory address of var. While reference I'm still unsure of its uses.

The difference between a pointer and a reference is paper-thin: a pointer contains a memory address (so you can edit the memory address itself, if needed), while a reference is some kind of "alias" for an already-existing variable (and it's implemented by storing the memory address under the hood, just like a pointer).

> You are seeking a Vertex* instead of a Vertex&, so you need to use & at the left side of (*bubbles)[] so that you pass the memory address.

That's essentially it. I explicitly ask C++ for the memory address.

> Sorry if I said something barbaric. The docs say:
>
> >sf::VertexArray is a very simple wrapper around a dynamic array of vertices and a primitives type.
>
>My mind kind of puts them around a similar place to a std::vector. On std::vector one can use push_back, which also reminds me to Python's list.append(). Furthermore, I seem to recall that std::vector uses Template, and I figured that the Primitive::Quads were similar to the T of the template.

You said nothing "barbaric", SFML's implementation is just a bit tricky, but you actually are a lot closer than you think.

https://github.com/SFML/SFML/blob/9bdf2078181954e06d88d84a0dbe7bbd5652f4fc/include/SFML/Graphics/VertexArray.hpp#L187

As you can see here there actually is an instance of `std::vector`, but `PrimitiveType` is just used to define the primitive to draw (which will be passed to the actual drawing subsystem).

**Comment by abreathingcorpse** [comment]
> As you can see here there actually is an instance of std::vector, but PrimitiveType is just used to define the primitive to draw (which will be passed to the actual drawing subsystem).

I see! So a `VertexArray` is simply a std::vector of `Vertex`.

As always, thank you for your time. I feel like I've been learning a ton ever since I began writing to you.

**Comment by Penaz91** [comment]
You're welcome. Glad to be of help!

Feel free to ask any other questions that come to mind!
